import { Level } from './types';

export const LEVELS: Level[] = [
  // EASY - 3x3 grids
  {
    id: 1,
    name: "First Steps",
    gridSize: 3,
    difficulty: 'easy',
    par: 2,
    monsters: [
      { color: 'pink', rowStart: 0, rowEnd: 0, colStart: 0, colEnd: 0 },
      { color: 'blue', rowStart: 0, rowEnd: 0, colStart: 2, colEnd: 2 },
    ],
    stars: [{ row: 0, col: 1 }],
  },
  {
    id: 2,
    name: "Slide Together",
    gridSize: 3,
    difficulty: 'easy',
    par: 2,
    monsters: [
      { color: 'pink', rowStart: 1, rowEnd: 1, colStart: 0, colEnd: 0 },
      { color: 'blue', rowStart: 1, rowEnd: 1, colStart: 2, colEnd: 2 },
      { color: 'green', rowStart: 0, rowEnd: 0, colStart: 1, colEnd: 1 },
    ],
    stars: [{ row: 1, col: 1 }, { row: 0, col: 1 }],
  },
  {
    id: 3,
    name: "Corner Play",
    gridSize: 4,
    difficulty: 'easy',
    par: 3,
    monsters: [
      { color: 'pink', rowStart: 0, rowEnd: 0, colStart: 0, colEnd: 0 },
      { color: 'blue', rowStart: 3, rowEnd: 3, colStart: 3, colEnd: 3 },
      { color: 'yellow', rowStart: 0, rowEnd: 0, colStart: 3, colEnd: 3 },
    ],
    stars: [{ row: 0, col: 1 }, { row: 0, col: 2 }, { row: 3, col: 2 }],
  },
  {
    id: 4,
    name: "Star Cluster",
    gridSize: 4,
    difficulty: 'easy',
    par: 3,
    monsters: [
      { color: 'pink', rowStart: 0, rowEnd: 0, colStart: 0, colEnd: 0 },
      { color: 'blue', rowStart: 0, rowEnd: 0, colStart: 3, colEnd: 3 },
      { color: 'green', rowStart: 3, rowEnd: 3, colStart: 0, colEnd: 0 },
    ],
    stars: [
      { row: 0, col: 1 }, { row: 0, col: 2 },
      { row: 1, col: 0 }, { row: 2, col: 0 },
    ],
  },
  {
    id: 5,
    name: "The Bridge",
    gridSize: 4,
    difficulty: 'easy',
    par: 3,
    monsters: [
      { color: 'pink', rowStart: 2, rowEnd: 2, colStart: 0, colEnd: 0 },
      { color: 'blue', rowStart: 2, rowEnd: 2, colStart: 3, colEnd: 3 },
      { color: 'yellow', rowStart: 0, rowEnd: 0, colStart: 1, colEnd: 1 },
      { color: 'green', rowStart: 3, rowEnd: 3, colStart: 2, colEnd: 2 },
    ],
    stars: [
      { row: 2, col: 1 }, { row: 2, col: 2 },
    ],
  },
  // MEDIUM - 4x4 and 5x5 grids
  {
    id: 6,
    name: "Four Corners",
    gridSize: 4,
    difficulty: 'medium',
    par: 4,
    monsters: [
      { color: 'pink', rowStart: 0, rowEnd: 0, colStart: 0, colEnd: 0 },
      { color: 'blue', rowStart: 0, rowEnd: 0, colStart: 3, colEnd: 3 },
      { color: 'green', rowStart: 3, rowEnd: 3, colStart: 0, colEnd: 0 },
      { color: 'yellow', rowStart: 3, rowEnd: 3, colStart: 3, colEnd: 3 },
    ],
    stars: [
      { row: 0, col: 1 }, { row: 0, col: 2 },
      { row: 3, col: 1 }, { row: 3, col: 2 },
      { row: 1, col: 0 }, { row: 2, col: 0 },
    ],
  },
  {
    id: 7,
    name: "Crossroads",
    gridSize: 5,
    difficulty: 'medium',
    par: 4,
    monsters: [
      { color: 'pink', rowStart: 2, rowEnd: 2, colStart: 0, colEnd: 0 },
      { color: 'blue', rowStart: 2, rowEnd: 2, colStart: 4, colEnd: 4 },
      { color: 'green', rowStart: 0, rowEnd: 0, colStart: 2, colEnd: 2 },
      { color: 'yellow', rowStart: 4, rowEnd: 4, colStart: 2, colEnd: 2 },
    ],
    stars: [
      { row: 2, col: 1 }, { row: 2, col: 2 }, { row: 2, col: 3 },
      { row: 1, col: 2 }, { row: 3, col: 2 },
    ],
  },
  {
    id: 8,
    name: "Diagonal Chase",
    gridSize: 5,
    difficulty: 'medium',
    par: 5,
    monsters: [
      { color: 'pink', rowStart: 0, rowEnd: 0, colStart: 0, colEnd: 0 },
      { color: 'blue', rowStart: 2, rowEnd: 2, colStart: 2, colEnd: 2 },
      { color: 'green', rowStart: 4, rowEnd: 4, colStart: 4, colEnd: 4 },
      { color: 'purple', rowStart: 0, rowEnd: 0, colStart: 4, colEnd: 4 },
    ],
    stars: [
      { row: 0, col: 1 }, { row: 0, col: 2 }, { row: 0, col: 3 },
      { row: 1, col: 2 }, { row: 3, col: 2 }, { row: 4, col: 2 },
    ],
  },
  {
    id: 9,
    name: "The Squeeze",
    gridSize: 5,
    difficulty: 'medium',
    par: 5,
    monsters: [
      { color: 'pink', rowStart: 1, rowEnd: 1, colStart: 0, colEnd: 0 },
      { color: 'blue', rowStart: 1, rowEnd: 1, colStart: 4, colEnd: 4 },
      { color: 'green', rowStart: 3, rowEnd: 3, colStart: 0, colEnd: 0 },
      { color: 'yellow', rowStart: 3, rowEnd: 3, colStart: 4, colEnd: 4 },
      { color: 'purple', rowStart: 0, rowEnd: 0, colStart: 2, colEnd: 2 },
    ],
    stars: [
      { row: 1, col: 1 }, { row: 1, col: 2 }, { row: 1, col: 3 },
      { row: 3, col: 1 }, { row: 3, col: 2 }, { row: 3, col: 3 },
    ],
  },
  {
    id: 10,
    name: "Star Formation",
    gridSize: 5,
    difficulty: 'medium',
    par: 6,
    monsters: [
      { color: 'pink', rowStart: 0, rowEnd: 0, colStart: 0, colEnd: 0 },
      { color: 'blue', rowStart: 0, rowEnd: 0, colStart: 4, colEnd: 4 },
      { color: 'green', rowStart: 4, rowEnd: 4, colStart: 0, colEnd: 0 },
      { color: 'yellow', rowStart: 4, rowEnd: 4, colStart: 4, colEnd: 4 },
      { color: 'purple', rowStart: 2, rowEnd: 2, colStart: 2, colEnd: 2 },
    ],
    stars: [
      { row: 0, col: 2 },
      { row: 2, col: 0 }, { row: 2, col: 4 },
      { row: 4, col: 2 },
      { row: 1, col: 2 }, { row: 3, col: 2 },
    ],
  },
  // HARD - 5x5 and 6x6 grids
  {
    id: 11,
    name: "Labyrinth",
    gridSize: 5,
    difficulty: 'hard',
    par: 7,
    monsters: [
      { color: 'pink', rowStart: 0, rowEnd: 0, colStart: 0, colEnd: 0 },
      { color: 'blue', rowStart: 0, rowEnd: 0, colStart: 4, colEnd: 4 },
      { color: 'green', rowStart: 4, rowEnd: 4, colStart: 0, colEnd: 0 },
      { color: 'yellow', rowStart: 4, rowEnd: 4, colStart: 4, colEnd: 4 },
      { color: 'purple', rowStart: 2, rowEnd: 2, colStart: 0, colEnd: 0 },
    ],
    stars: [
      { row: 0, col: 1 }, { row: 0, col: 2 }, { row: 0, col: 3 },
      { row: 2, col: 1 }, { row: 2, col: 2 }, { row: 2, col: 3 },
      { row: 4, col: 1 }, { row: 4, col: 2 },
    ],
  },
  {
    id: 12,
    name: "Master Plan",
    gridSize: 6,
    difficulty: 'hard',
    par: 7,
    monsters: [
      { color: 'pink', rowStart: 0, rowEnd: 0, colStart: 0, colEnd: 0 },
      { color: 'blue', rowStart: 0, rowEnd: 0, colStart: 5, colEnd: 5 },
      { color: 'green', rowStart: 5, rowEnd: 5, colStart: 0, colEnd: 0 },
      { color: 'yellow', rowStart: 5, rowEnd: 5, colStart: 5, colEnd: 5 },
      { color: 'purple', rowStart: 2, rowEnd: 2, colStart: 2, colEnd: 2 },
      { color: 'pink', rowStart: 3, rowEnd: 3, colStart: 3, colEnd: 3 },
    ],
    stars: [
      { row: 0, col: 2 }, { row: 0, col: 3 },
      { row: 2, col: 0 }, { row: 2, col: 5 },
      { row: 3, col: 0 }, { row: 3, col: 5 },
      { row: 5, col: 2 }, { row: 5, col: 3 },
    ],
  },
  {
    id: 13,
    name: "Tangled Web",
    gridSize: 6,
    difficulty: 'hard',
    par: 8,
    monsters: [
      { color: 'pink', rowStart: 0, rowEnd: 0, colStart: 0, colEnd: 0 },
      { color: 'blue', rowStart: 0, rowEnd: 0, colStart: 3, colEnd: 3 },
      { color: 'green', rowStart: 3, rowEnd: 3, colStart: 0, colEnd: 0 },
      { color: 'yellow', rowStart: 5, rowEnd: 5, colStart: 5, colEnd: 5 },
      { color: 'purple', rowStart: 2, rowEnd: 2, colStart: 5, colEnd: 5 },
      { color: 'blue', rowStart: 5, rowEnd: 5, colStart: 2, colEnd: 2 },
    ],
    stars: [
      { row: 0, col: 1 }, { row: 0, col: 2 },
      { row: 3, col: 1 }, { row: 3, col: 2 },
      { row: 2, col: 3 }, { row: 2, col: 4 },
      { row: 5, col: 3 }, { row: 5, col: 4 },
    ],
  },
  {
    id: 14,
    name: "Chaos Theory",
    gridSize: 6,
    difficulty: 'hard',
    par: 9,
    monsters: [
      { color: 'pink', rowStart: 0, rowEnd: 0, colStart: 1, colEnd: 1 },
      { color: 'blue', rowStart: 1, rowEnd: 1, colStart: 0, colEnd: 0 },
      { color: 'green', rowStart: 0, rowEnd: 0, colStart: 4, colEnd: 4 },
      { color: 'yellow', rowStart: 1, rowEnd: 1, colStart: 5, colEnd: 5 },
      { color: 'purple', rowStart: 4, rowEnd: 4, colStart: 0, colEnd: 0 },
      { color: 'pink', rowStart: 5, rowEnd: 5, colStart: 1, colEnd: 1 },
      { color: 'blue', rowStart: 4, rowEnd: 4, colStart: 5, colEnd: 5 },
    ],
    stars: [
      { row: 0, col: 2 }, { row: 0, col: 3 },
      { row: 1, col: 2 }, { row: 1, col: 3 },
      { row: 4, col: 2 }, { row: 4, col: 3 },
      { row: 5, col: 2 }, { row: 5, col: 3 },
    ],
  },
  {
    id: 15,
    name: "Grand Finale",
    gridSize: 6,
    difficulty: 'hard',
    par: 10,
    monsters: [
      { color: 'pink', rowStart: 0, rowEnd: 0, colStart: 0, colEnd: 0 },
      { color: 'blue', rowStart: 0, rowEnd: 0, colStart: 5, colEnd: 5 },
      { color: 'green', rowStart: 5, rowEnd: 5, colStart: 0, colEnd: 0 },
      { color: 'yellow', rowStart: 5, rowEnd: 5, colStart: 5, colEnd: 5 },
      { color: 'purple', rowStart: 0, rowEnd: 0, colStart: 2, colEnd: 2 },
      { color: 'pink', rowStart: 2, rowEnd: 2, colStart: 0, colEnd: 0 },
      { color: 'blue', rowStart: 5, rowEnd: 5, colStart: 3, colEnd: 3 },
    ],
    stars: [
      { row: 0, col: 1 }, { row: 0, col: 3 }, { row: 0, col: 4 },
      { row: 1, col: 0 }, { row: 1, col: 5 },
      { row: 2, col: 2 }, { row: 2, col: 5 },
      { row: 3, col: 0 }, { row: 3, col: 5 },
      { row: 4, col: 0 }, { row: 4, col: 5 },
      { row: 5, col: 1 }, { row: 5, col: 2 }, { row: 5, col: 4 },
    ],
  },
];
